FROM python:3.12-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

#ENV DB_HOST=localhost
#ENV DB_PORT=5432
#ENV DB_NAME=postgres
#ENV DB_USERNAME=postgres
#ENV DB_PASSWORD=password

#EXPOSE 8000

WORKDIR /opt/banking-project

COPY ../src src
COPY ../scripts scripts
COPY ../pyproject.toml pyproject.toml

RUN uv sync

ENTRYPOINT [ "uv", "run" ]

CMD [ "sh", "scripts/run_etl.sh" ]
