FROM python:3.12-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

EXPOSE 8000

WORKDIR /opt/banking-project

COPY ../src src
COPY ../scripts scripts
COPY ../pyproject.toml pyproject.toml

RUN uv sync

ENTRYPOINT [ "uv", "run" ]

CMD [ "sh", "scripts/run_etl.sh" ]
