def month_to_integer(month: str) -> int:
    return MONTHS.get(month.lower().strip().rstrip())

MONTHS = {
    "jan": 1,
    "january": 1,
    "januar": 1,
    "feb": 2,
    "february": 2,
    "februar": 2,
    "mar": 3,
    "march": 3,
    "mart": 3,
    "apr": 4,
    "april": 4,
    "may": 5,
    "maj": 5,
    "jun": 6,
    "june": 6,
    "jul": 7,
    "july": 7,
    "aug": 8,
    "august": 8,
    "avgust": 8,
    "sep": 9,
    "september": 9,
    "septamber": 9,
    "oct": 10,
    "october": 10,
    "oktobar": 10,
    "nov": 11,
    "november": 11,
    "novembar": 11,
    "dec": 12,
    "december": 12,
    "decembar": 12,
}
